### ISSUE TITLE
Multiple calls to validate() cause duplicate messages

### ISSUE THREAD

**Issue by mattrothenberg** [davwards/valchemy#1]
To reproduce:

````javascript
var basicValidation = new v.BasicValidation()
      .length(10).withMessage("Too short");

basicValidation.validate('short');
basicValidation.validate('short').messages; // ['Too short', 'Too short']
````

As of https://github.com/davwards/valchemy/commit/8b8d90b5d426b0cbe39fb211f81b83182c6a16b6

**Comment by davwards** [comment]
+1

**Comment by davwards** [comment]
I think the resolution for https://github.com/davwards/valchemy/issues/3 might drive this out as well

**Comment by mattrothenberg** [comment]
Fixed by https://github.com/davwards/valchemy/commit/5b4730bf6387708b201f62372d291e6347c64cad
