### ISSUE TITLE
Presence Validator

### ISSUE THREAD

**Issue by mattrothenberg** [davwards/valchemy#9]
Hello,

A code sample in the README suggests that there is a `present()` validator which can be chained together with other validators.

```
var Validation = require('valchemy');
firstNameValidation = Validation().present().maxLength(10);
```

I can't seem to find this Validator anywhere. I do see an `ifPresent()` modifier, though. 

Am I missing something?

**Comment by davwards** [comment]
Uh wow, you are definitely not missing something, but the library is. I could have sworn we had that one already!

**Comment by davwards** [comment]
This would be a great pull request for a first time contributor.

Desired behavior for the `present` validator would probably be:
- Validation fails on `null`, `undefined`, or `''`.
- Validation passes otherwise.
